apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: test-techtrends
  name: test-techtrends
  namespace: {{ .Values.namespace.name}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: test-techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-techtrends
    spec:
      containers:
      - image: barhome/{{ .Values.image.repository}}:{{ .Values.image.tag}}
        imagePullPolicy: {{ .Values.image.pullPolicy}}
        name: test-techtrends
        ports:
        - containerPort: 3111
          protocol: TCP
        
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory}}
            cpu: {{ .Values.resources.requests.CPU}}
          limits:
            memory: {{ .Values.resources.limits.memory}}
            cpu: {{ .Values.resources.limits.CPU}}
