apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: test-techtrends
  name: test-techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-techtrends
    spec:
      containers:
      - image: barhome/test-techtrends:latest
        imagePullPolicy: Always
        name: test-techtrends
        ports:
        - containerPort: 3111
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
