apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-techtrends
  name: test-techtrends
  namespace: sandbox
spec:
  ports:
  - name: 4111-3111
    port: 4111
    protocol: TCP
    targetPort: 3111
    nodePort: 30009
  selector:
    app: test-techtrends
  type: NodePort
status:
  loadBalancer: {}
