apiVersion: v1
name: test-techtrends 
description: Install a Python test-techtrends app deployment
keywords:
- python
- test-techtrends 
version: 1.0.0
maintainers:
- name: barhome 
  email: barhome@github.com
